name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm --version
        node --version
        npm install

    - name: List files
      run: |
        ls -la
        ls -la tests/
        ls -la tests/__mocks__ || true

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Run test coverage
      run: npm run test:coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}